driver:
  enabled: false
  # version: "560.35.03"
  # env:
  # - name: http_proxy
  #   value: http://127.0.0.1:3128
  # - name: https_proxy
  #   value: http://127.0.0.1:3128
  # - name: no_proxy
  #   value: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  # rdma:
  #   enabled: true
  #   useHostMofed: true
  repoConfig:
    configMapName: repo-config
  ## close GPU GSP (optional)
  kernelModuleConfig:
    name: "kernel-module-params"

nfd:
  enabled: false

toolkit:
  env:
    - name: CONTAINERD_CONFIG
      value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    - name: CONTAINERD_SOCKET
      value: /run/k3s/containerd/containerd.sock
    - name: CONTAINERD_RUNTIME_CLASS
      value: nvidia
    - name: CONTAINERD_SET_AS_DEFAULT
      value: "true"
    - name: NVIDIA_CONTAINER_RUNTIME_LOG_LEVEL
      value: "warning"

daemonsets:
  tolerations:
    - operator: Exists
      effect: NoSchedule 

operator:
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 100Mi
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists

dcgmExporter:
  env:
    - name: DCGM_EXPORTER_LISTEN
      value: ":9400"
    - name: DCGM_EXPORTER_KUBERNETES
      value: "true"
  config:
    name: dcgm-exporter-config
