apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public
  namespace: dynamo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  #storageClassName: xxx
