---
- name: Create k3s-node.service.d directory
  ansible.builtin.file:
    path: "{{ systemd_dir }}/k3s-node.service.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy K3s tls conf file
  ansible.builtin.template:
    src: tls.conf.j2
    dest: "{{ systemd_dir }}/k3s-node.service.d/tls.conf"
    owner: root
    group: root
    mode: "0755"
