apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod
spec:
  restartPolicy: OnFailure
  containers:
    - image: mellanox/rping-test
      name: mofed-test-ctr
      securityContext:
        capabilities:
          add: ["IPC_LOCK"]
      resources:
        limits:
          rdma/ib: 1
      command:
        - sh
        - -c
        - |
          ls -l /dev/infiniband /sys/class/infiniband /sys/class/net
          sleep 1000000
