apiVersion: v1
kind: Secret
metadata:
  name: juicefs-prd-secret
  labels:
    # 增加该标签以启用认证信息校验
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: juicefs-prd
  metaurl: "tikv://172.19.12.1:2379,172.19.12.2:2379,172.19.12.3:2379/juicefs-prd?ca=/etc/tikv/ca.crt&cert=/etc/tikv/client.crt&key=/etc/tikv/client.pem"
  configs: "{ceph-prd-conf: /etc/ceph, tikv-prd-tls: /etc/tikv}"
  storage: ceph
  bucket: ceph://juicefs-prd
  access-key: "ceph"
  secret-key: "client.juicefs-prd"
  envs: "{TZ: Asia/Shanghai}"
  # 如需在 Mount Pod 中创建文件系统，也可以将更多 juicefs format 参数填入 format-options。
  # format-options: trash-days=1,block-size=4096