apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: kube-system
  annotations:
    metallb.universe.tf/address-pool: default
    # 修改为实际分配的 vip, 一般选择 metallb ip pool 最后一个地址
    metallb.universe.tf/loadBalancerIPs: 172.18.15.199
spec:
  ports:
  - name: https
    port: 6443
    protocol: TCP
    targetPort: 6443
  type: LoadBalancer
---
apiVersion: v1
kind: Endpoints
metadata:
  name: apiserver
  namespace: kube-system
subsets:
- addresses:
  # 修改为实际的 apiserver 成员节点 IP
  - ip: 172.18.15.101
  - ip: 172.18.15.102
  - ip: 172.18.15.103
  ports:
  - name: https
    port: 6443
    protocol: TCP