apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- files:
  - ceph.conf=ceph/ceph.conf
  - ceph.client.juicefs-prd.keyring=ceph/ceph.client.juicefs-prd.keyring
  name: ceph-prd-conf
  options:
    disableNameSuffixHash: true
  type: Opaque
- files:
  - ca.crt=tikv/ca.crt
  - client.crt=tikv/client.crt
  - client.pem=tikv/client.pem
  name: tikv-prd-tls
  options:
    disableNameSuffixHash: true
  type: Opaque
namespace: juicefs
resources:
- secret.yaml
- storageclass.yaml
